// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {toggltrack} from '../models';
import {cfg} from '../models';
import {api} from '../models';

export function CanSynchronize():Promise<boolean>;

export function LoadConfig():Promise<main.LoadedConfig>;

export function LoadTasks(arg1:string,arg2:string):Promise<toggltrack.AskedTasks>;

export function SaveConfig(arg1:cfg.Config):Promise<void>;

export function SynchronizeTasks(arg1:Array<toggltrack.AppTask>):Promise<void>;

export function TestCredentials():Promise<api.CredentialsTest>;
