// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {cfg} from '../models';

export function CanSynchronize():Promise<boolean>;

export function LoadConfig():Promise<cfg.Config>;

export function SaveConfig(arg1:cfg.Config):Promise<boolean>;
