// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {cfg} from '../models';
import {toggltrack} from '../models';
import {api} from '../models';

export function CanSynchronize():Promise<boolean>;

export function LoadConfig():Promise<cfg.Config>;

export function LoadTasks(arg1:string,arg2:string):Promise<toggltrack.AppTasks>;

export function SaveConfig(arg1:cfg.Config):Promise<boolean>;

export function TestCredentials():Promise<api.CredentialsTest>;
