// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CanSynchronize() {
  return window['go']['main']['App']['CanSynchronize']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function LoadTasks(arg1, arg2) {
  return window['go']['main']['App']['LoadTasks'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SynchronizeTasks(arg1) {
  return window['go']['main']['App']['SynchronizeTasks'](arg1);
}

export function TestCredentials() {
  return window['go']['main']['App']['TestCredentials']();
}
