name: Wails build

on:
    push:
        tags:
            - '*'

jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                build: [
                    { name: toggl-redmine, platform: linux/amd64, os: ubuntu-latest, tags: 'webkit2_41' },
                    { name: toggl-redmine, platform: darwin/universal, os: macos-latest }
                ]
        runs-on: ${{ matrix.build.os }}
        steps:
            -   uses: actions/checkout@v4
                with:
                    submodules: recursive
            -   name: Installation de libwebkit2gtk-4.1-dev
                if: "${{ matrix.build.platform == 'linux/amd64' }}"
                run: sudo apt install -y libwebkit2gtk-4.1-dev
            -   uses: DjLeChuck/wails-build-action@feature/allow-wails-build-tags
                with:
                    build-name: ${{ matrix.build.name }}
                    build-platform: ${{ matrix.build.platform }}
                    build-tags: ${{ matrix.build.tags }}
                    sign: false
