name: Wails build

on: [workflow_dispatch]

jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                build: [
                    { name: toggl-redmine, platform: linux/amd64, os: ubuntu-latest, name_suffix: '' },
                    { name: toggl-redmine, platform: darwin/arm64, os: macos-latest, name_suffix: ' - arm64' },
                    { name: toggl-redmine, platform: darwin/amd64, os: macos-latest, name_suffix: ' - amd64' }
                ]
        runs-on: ${{ matrix.build.os }}
        steps:
            -   uses: actions/checkout@v2
                with:
                    submodules: recursive
            -   uses: dAppServer/wails-build-action@v2.2
                with:
                    build-name: ${{ matrix.build.name }}${{ matrix.build.name_suffix }}
                    build-platform: ${{ matrix.build.platform }}
                    sign: false
